version: '3.5'

services:
  redis:
    image: 'redis:5-alpine'
    command: redis-server
    volumes:
      - 'redis:/data'

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL_CACHING=redis://redis:6379/0
volumes:
  redis: